apiVersion: v2
name: opsarmor
description: Scheduled agentless Linux vulnerability scans using OpsArmor
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/Cloudopsshell/OpsArmor
sources:
  - https://github.com/Cloudopsshell/OpsArmor
keywords:
  - security
  - vulnerability-scanning
  - linux
maintainers:
  - name: CloudOpsShell
    url: https://github.com/Cloudopsshell